# Generated by Django 4.0.6 on 2022-08-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_bienvenue_image_bienvenue_mail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bienvenue',
            name='mailo',
        ),
        migrations.AlterField(
            model_name='bienvenue',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
